language: ruby

os: linux

sudo: false

bundler_args: --jobs 4 --retry 2 --without packaging documentation

before_install:
  gem update --system --force
  
script:
  - "bundle exec rake $CHECK"

notifications:
  email: false

matrix:
  include:
    - rvm: 2.3
      env: "CHECK=parallel:spec\\[2\\]"
      arch: 
        - amd64
        - ppc64le

    - rvm: 2.4
      env: "CHECK=parallel:spec\\[2\\]"
      arch: 
        - amd64
        - ppc64le

    - rvm: 2.5
      env: "CHECK=parallel:spec\\[2\\]"
      arch: 
        - amd64
        - ppc64le

    - rvm: 2.6
      env: "CHECK=parallel:spec\\[2\\]"
      arch: 
        - amd64
        - ppc64le

    - rvm: jruby-9.2.8.0
      jdk: openjdk8
      env:
        - "_JAVA_OPTIONS='-Xmx1024m -Xms512m'"
        - "CHECK=parallel:spec\\[2\\]"
      arch: 
        - amd64
        - ppc64le

    - rvm: 2.5
      env: "CHECK=rubocop"
      arch: 
        - amd64
        - ppc64le

    - rvm: 2.5
      env: "CHECK=commits"
      arch: 
        - amd64
        - ppc64le
        
    - rvm: 2.5
      env: "CHECK=warnings"
      arch: 
        - amd64
        - ppc64le
